### ISSUE TITLE
Problems with torrent serialization(IE, error when running new Torrent(bytes, seed))

### ISSUE THREAD

**Issue by tchoulihan** [mpetazzoni/ttorrent#131]
I've been testing out serializing and deserializing torrents with methods I found here, but I keep getting an error upon deserialization(IE, running `new Torrent(bytes, seed)`:
```
com.turn.ttorrent.bcodec.InvalidBEncodingException: Unknown indicator '99'
	at com.turn.ttorrent.bcodec.BDecoder.bdecode(BDecoder.java:142)
	at com.turn.ttorrent.bcodec.BDecoder.bdecodeMap(BDecoder.java:278)
	at com.turn.ttorrent.bcodec.BDecoder.bdecode(BDecoder.java:140)
	at com.turn.ttorrent.bcodec.BDecoder.bdecodeMap(BDecoder.java:280)
	at com.turn.ttorrent.bcodec.BDecoder.bdecode(BDecoder.java:140)
	at com.turn.ttorrent.bcodec.BDecoder.bdecode(BDecoder.java:88)
	at com.turn.ttorrent.common.Torrent.<init>(Torrent.java:137)
```

Here's how I'm using it:
Serializing:
```java
public static String serializeTorrentFile(Torrent t) {

		String out = null;
		try {
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			t.save(baos);

			out = baos.toString("UTF-8");
			baos.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return out;
	}
```
Deserializing:
```java
	public static Torrent deserializeTorrentFile(String data) {
		Torrent t = null;
		try {
			byte[] b = data.getBytes("UTF-8");
			t = new Torrent(b, false); // ERROR COMES ON THIS LINE
			
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return t;
	}
```

**Comment by mpetazzoni** [comment]
I don't think you can reliably convert and read back the binary torrent data as a UTF-8 encoded String. Does it work when you use `byte[]` ?

See https://github.com/mpetazzoni/ttorrent/blob/master/core/src/main/java/com/turn/ttorrent/common/Torrent.java#L493

**Comment by tchoulihan** [comment]
That did it @mpetazzoni, if I keep it as a byte[] , but not as a UTF-8 string.
