### ISSUE TITLE
IllegalStateException: Trying to download a piece while previous download not completed!

### ISSUE THREAD

**Issue by chrisawad** [mpetazzoni/ttorrent#164]
I'm getting the following all over the place when I download a torrent using the master branch right now.

Thoughts?

```
Exception in thread "bt-peer(..BC5A6F)-recv" java.lang.IllegalStateException: Trying to download a piece while previous download not completed!
	at com.turn.ttorrent.client.peer.SharingPeer.downloadPiece(SharingPeer.java:357)
	at com.turn.ttorrent.client.SharedTorrent.handlePeerReady(SharedTorrent.java:700)
	at com.turn.ttorrent.client.peer.SharingPeer.firePeerReady(SharingPeer.java:654)
	at com.turn.ttorrent.client.peer.SharingPeer.handleMessage(SharingPeer.java:615)
	at com.turn.ttorrent.client.peer.PeerExchange$IncomingThread.run(PeerExchange.java:364)
```

**Comment by abreksa4** [comment]
+1

**Comment by mianharisali** [comment]
+1

**Comment by henkel** [comment]
Could that issue be related to #173 byteArrayToHexString return wrong result? Fix #174 was merged to master.

**Comment by saibbyweb** [comment]
+1

**Comment by LIXUANYI** [comment]
+1

**Comment by yorlov** [comment]
+1

**Comment by LazyDoge** [comment]
+1

**Comment by mdeanda** [comment]
took a look at the code and it seems like a rather simple fix and it might actually be an issue where the current implementation might not download a requested piece (need to double check this accusation though).

the method `handlePeerReady(SharingPeer peer)` is called in 2 places and one of them already checks if the peer is currently downloading. it makes more sense to add a check for `isDownloading` in that handle peer ready method and break out quietly instead of doing anything in that method. my suggestion:

``` //SharedTorrent.java
	@Override
	public synchronized void handlePeerReady(SharingPeer peer) {
		if (peer.isDownloading()) return;

	// ... the existing body
	}
```

is this library being maintained still?
