### ISSUE TITLE
Please stop print this stack trace

### ISSUE THREAD

**Issue by icemagno** [mpetazzoni/ttorrent#169]
```
Exception in thread "bt-peer(..616563)-recv" java.nio.channels.CancelledKeyException
        at sun.nio.ch.SelectionKeyImpl.ensureValid(Unknown Source)
        at sun.nio.ch.SelectionKeyImpl.readyOps(Unknown Source)
        at java.nio.channels.SelectionKey.isReadable(Unknown Source)
        at com.turn.ttorrent.client.peer.PeerExchange$IncomingThread.read(PeerExchange.java:284)
        at com.turn.ttorrent.client.peer.PeerExchange$IncomingThread.run(PeerExchange.java:322)


```
I'm just closing Client and face this ST sometimes, even inside a TRY..CATCH block.

**Comment by TanJay** [comment]
could you submit the try catch block

**Comment by icemagno** [comment]
`even inside a TRY..CATCH block.` I think the author is printing the stack trace... `e.printStackTrace()` inside `PeerExchange.IncomingThread.read()`. Maybe related to #142

**Comment by henkel** [comment]
I cannot find printStackTrace() in the latest source code. Are you referring to version 1.4?

**Comment by icemagno** [comment]
This happens just sometimes and I can tell what is causing the error to raise. I think is because I'm trying to stop clients when serving to peers.
My try..catch block is very simple:

try {
    client.stop();
} catch ( Exception e ) {
    // ignore
}

Where `client` is `com.turn.ttorrent.client.Client`.
As you can see in my first post, there is no references to my code. Is all stack trace shown.
