### ISSUE TITLE
The POM for com.turn:ttorent-core:jar:1.5 is missing, no dependency information available

### ISSUE THREAD

**Issue by arjunthedragon** [mpetazzoni/ttorrent#216]
I am trying to integrate this library in my java project. But, unfortunately, i am not able to build using maven. 

It is saying that the package is missing for torrent-cli. Kindly help with the following. I am appending the stack trace below.

```
[INFO] Building jar: /home/arjun/Dragon Realm/Workspace/nitt_lab_works/ns_lab/github_repos/ttorrent/core/target/ttorrent-core-1.6-SNAPSHOT-javadoc.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Java BitTorrent library CLI 1.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.turn:ttorent-core:jar:1.5 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Java BitTorrent library ............................ SUCCESS [  0.725 s]
[INFO] Java BitTorrent library core ....................... SUCCESS [  5.245 s]
[INFO] Java BitTorrent library CLI ........................ FAILURE [  0.028 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.152 s
[INFO] Finished at: 2018-04-07T18:27:03+05:30
[INFO] Final Memory: 20M/249M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ttorrent-cli: Could not resolve dependencies for project com.turn:ttorrent-cli:jar:1.6-SNAPSHOT: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ttorrent-cli: Could not resolve dependencies for project com.turn:ttorrent-cli:jar:1.6-SNAPSHOT: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.turn:ttorrent-cli:jar:1.6-SNAPSHOT: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.turn:ttorent-core:jar:1.5 in https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-thirdparty-releases has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ttorrent-cli

```

**Comment by mpetazzoni** [comment]
Hmm, they're all available for version 1.5: http://search.maven.org/#search|ga|1|ttorrent

Can you try with `mvn -U` ?
