### ISSUE TITLE
Large files (more then 2GB) not supported in v2.0

### ISSUE THREAD

**Issue by potapenko** [mpetazzoni/ttorrent#222]
```
java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
	at com.turn.ttorrent.client.storage.FairPieceStorageFactory.createStorage(FairPieceStorageFactory.java:40)
	at com.turn.ttorrent.client.CommunicationManager.addTorrent(CommunicationManager.java:146)
	at com.turn.ttorrent.client.CommunicationManager.addTorrent(CommunicationManager.java:127)
	at com.turn.ttorrent.client.SimpleClient.startDownloading(SimpleClient.java:71)
	at com.turn.ttorrent.client.SimpleClient.downloadTorrentAsync(SimpleClient.java:77)

```

**Comment by Dead-off** [comment]
thank you! Fixed
