### ISSUE TITLE
Can't download - Invalid metadata format. Map doesn't contain required field announce

### ISSUE THREAD

**Issue by vikulin** [mpetazzoni/ttorrent#231]
com.turn.ttorrent.bcodec.InvalidBEncodingException: Invalid metadata format. Map doesn't contain required field announce
	at com.turn.ttorrent.common.TorrentParser.getRequiredValueOrThrowException(TorrentParser.java:159)
	at com.turn.ttorrent.common.TorrentParser.parse(TorrentParser.java:51)
	at com.turn.ttorrent.common.TorrentParser.parseFromFile(TorrentParser.java:23)
	at com.turn.ttorrent.client.FileMetadataProvider.getTorrentMetadata(FileMetadataProvider.java:22)
	at com.turn.ttorrent.client.CommunicationManager.addTorrent(CommunicationManager.java:174)
	at com.turn.ttorrent.client.CommunicationManager.addTorrent(CommunicationManager.java:156)
	at com.turn.ttorrent.client.CommunicationManager.addTorrent(CommunicationManager.java:127)
	at com.turn.ttorrent.client.SimpleClient.startDownloading(SimpleClient.java:71)
	at com.turn.ttorrent.client.SimpleClient.downloadTorrent(SimpleClient.java:58)
	at org.hyperborian.bt.client.App.main(App.java:24)

My simple code
public class App {
    public static void main( String[] args ) throws UnknownHostException {
    	
    	// First, instantiate the Client object.
    	SimpleClient client = new SimpleClient();

    	// This is the interface the client will listen on (you might need something
    	// else than localhost here because other peers cannot connect to localhost).
    	InetAddress address = InetAddress.getLocalHost();

    	//Start download. Thread is blocked here
    	try {
    	  client.downloadTorrent("C:\\Users\\Vadym\\Downloads\\example.torrent",
    	          "~\\Downloads",
    	          address);
    	  //download finished
    	} catch (Exception e) {
    	  //download failed, see exception for details
    	  e.printStackTrace();
    	}
    	//If you don't want to seed the torrent you can stop client
    	client.stop();	
    }
}

Torrent file is a valid and susscessfully downloaded from uTorrent client

**Comment by Dead-off** [comment]
can you attach torrent file please?

**Comment by vikulin** [comment]
Sure. Torrent file attached,

пн, 12 нояб. 2018 г. в 10:08, Maxim Zaytsev <notifications@github.com>:

**Comment by Dead-off** [comment]
hmm, i don't see it. If you answered via email looks like github doesn't support providing files  from mail to issue. Can you attach file here?

**Comment by vikulin** [comment]
Attached.

[example.zip](https://github.com/mpetazzoni/ttorrent/files/2571569/example.zip)

**Comment by vikulin** [comment]
Ok. I hope the DHT support is going to be added soon.

пн, 12 нояб. 2018 г. в 13:21, Maxim Zaytsev <notifications@github.com>:

**Comment by Dead-off** [comment]
bug with parsing fixed, for DHT support exists other issue
https://github.com/mpetazzoni/ttorrent/issues/83
